export const lang = {
  app: {
    loading: 'Laster Inn...',
  },
  element: {
    email: 'E-post',
    password: 'Passord',
  },
  validation: {
    email: 'Vennligst skriv inn e-postadresse',
    password: 'Passordet må være minst 6 tegn',
    required: 'Påkrevd felt',
    noPasswordMatch: 'Passordene stemmer ikke overens',
    len: 'Kontonummer må være 11 siffer',
    validEmail: 'Inndata er ikke en gyldig e-post',
  },
  menu: {
    cases: 'Saker',
    settings: 'Innstillinger',
    profile: 'Min profil',
    logout: 'Logg ut',
  },
  login: {
    remember: 'Husk meg',
    login: 'Logg inn',
    forgotPassword: 'Glemt passord',
  },
  forgotPassword: {
    back: 'Tilbake',
    reset: 'Tilbakestill Passord',
    caption:
      'Vi vil sende en lenke for tilbakestilling av passord til din e-postadresse.',
  },
  footer: {
    copyright: '@2023 Petlink AS. Alle Rettigheter Reservert',
  },
  admin: {
    back: 'Tilbake',
    newVet: 'Ny veterinærer',
    newInsuranceCompany: 'Ny forsikringsselskap',
    contactInfo: 'Kontoinformasjon',
    clinlicName: 'Klinikkens navn',
    companyName: 'Selskapetsnavn',
    orgNumber: 'Organisasjonsnummer',
    personName: 'Kontaktperson',
    email: 'E-post',
    phone: 'Telefon',
    address: 'Adresse',
    bankInfo: 'Bankinformasjon',
    bankAccountNumber: 'Kontonummer',
    createPassword: 'Opprett passord',
    newPassword: 'Nytt passord',
    repeatPassword: 'Gjenta passord',
    create: 'Opprett',
    vets: 'Veterinærer',
    insuranceCompanies: 'Forsikringsselskaper',
    action: 'HANDLING',
    contact: 'KONTAKT',
    clinlic: 'Klinikk',
    company: 'Selskapets',
    orgNumberShort: 'ORG.NR',
    searchVets: 'Søk etter veterinærer',
    createVet: 'Opprett veterinærer',
    searchInsuranceCompanies: 'Søk etter forsikringsselskap',
    createInsuranceCompany: 'Opprett forsikringsselskap',
  },
  treat: {
    status: 'Status:',
    all: 'Vis alle',
    active: 'Aktive saker',
    approved: 'Godkjente saker',
    declined: 'Avslåtte saker',
    draft: 'Utkast saker',
    clinic: 'Klinikk:',
    treat: 'Saker',
    treatNo: 'ID',
    treatName: 'BEHANDLER',
    treatCaseNo: 'SAKSNR',
    treatClaimNo: 'SKADENR',
    treatConversation: 'SAMTALE',
    treatFiles: 'VEDLEGG',
    treatStatus: 'STATUS',
    createNewTreat: 'Opprett ny sak',
    myTreats: 'Mine saker',

    detail: {
      alertMessage: 'Konkluder saken',
      alertDescription:
        'Har Konklusjonen blitt nadd i saken? Velg "Fyll ut dekningsberettighet" eller "Gi avslag" ved a trykke pa knappen.',
      alertActionButton: 'Konkluder saken',
      completeTitle: 'Dekningsberettighet',
      completeContent:
        'Vurder saken som dekningsberettighet. Alle relevante konstnader vil bli dekket. Venningst fyll ut folgende poster med kostnader og beskrivelser. Du kan ogsa se hva veterinaeren har fylt ut.',
      completeButton: 'Dekningstilsagn',
      rejectTitle: 'Avslag',
      rejectContent:
        'Vennligst gi en kort begruunelse for avsaget og ga videre til neste sak. Nar du har fullført alle avslagene, kan du generere en oppsummering i form av en PDF med full oversikt over sakene.',
      rejectButton: 'Gi avslag',
    },
  },
};
