const actions = {
  GET_MY_TREATS: 'GET_MY_TREATS',
  GET_MY_TREATS_SUCCESS: 'GET_MY_TREATS_SUCCESS',
  GET_MY_TREATS_FAILURE: 'GET_MY_TREATS_FAILURE',

  GET_PET_CATEGORIES: 'GET_PET_CATEGORIES',
  GET_PET_CATEGORIES_SUCCESS: 'GET_PET_CATEGORIES_SUCCESS',
  GET_PET_CATEGORIES_FAILURE: 'GET_PET_CATEGORIES_FAILURE',

  GET_TREAT: 'GET_TREAT',
  GET_TREAT_SUCCESS: 'GET_TREAT_SUCCESS',
  GET_TREAT_FAILURE: 'GET_TREAT_FAILURE',

  GET_AVAILABLE_INSURANCE_COMPANIES: 'GET_AVAILABLE_INSURANCE_COMPANIES',
  GET_AVAILABLE_INSURANCE_COMPANIES_SUCCESS:
    'GET_AVAILABLE_INSURANCE_COMPANIES_SUCCESS',
  GET_AVAILABLE_INSURANCE_COMPANIES_FAILURE:
    'GET_AVAILABLE_INSURANCE_COMPANIES_FAILURE',

  SET_TREAT: 'SET_TREAT',

  DRAFT_TREAT: 'DRAFT_TREAT',
  DRAFT_TREAT_SUCCESS: 'DRAFT_TREAT_SUCCESS',
  DRAFT_TREAT_FAILURE: 'DRAFT_TREAT_FAILURE',

  CREATE_TREAT: 'CREATE_TREAT',
  CREATE_TREAT_SUCCESS: 'CREATE_TREAT_SUCCESS',
  CREATE_TREAT_FAILURE: 'CREATE_TREAT_FAILURE',

  UPDATE_TREAT: 'UPDATE_TREAT',
  UPDATE_TREAT_SUCCESS: 'UPDATE_TREAT_SUCCESS',
  UPDATE_TREAT_FAILURE: 'UPDATE_TREAT_FAILURE',

  UPDATE_TREAT_NUMBER: 'UPDATE_TREAT_NUMBER',
  UPDATE_TREAT_NUMBER_SUCCESS: 'UPDATE_TREAT_NUMBER_SUCCESS',
  UPDATE_TREAT_NUMBER_FAILURE: 'UPDATE_TREAT_NUMBER_FAILURE',

  REJECT_TREAT: 'REJECT_TREAT',
  REJECT_TREAT_SUCCESS: 'REJECT_TREAT_SUCCESS',
  REJECT_TREAT_FAILURE: 'REJECT_TREAT_FAILURE',

  COMPLETE_TREAT: 'COMPLETE_TREAT',
  COMPLETE_TREAT_SUCCESS: 'COMPLETE_TREAT_SUCCESS',
  COMPLETE_TREAT_FAILURE: 'COMPLETE_TREAT_FAILURE',

  DOWNLOAD_TREAT_OVERVIEW: 'DOWNLOAD_TREAT_OVERVIEW',
  DOWNLOAD_TREAT_OVERVIEW_SUCCESS: 'DOWNLOAD_TREAT_OVERVIEW_SUCCESS',
  DOWNLOAD_TREAT_OVERVIEW_FAILURE: 'DOWNLOAD_TREAT_OVERVIEW_FAILURE',

  DELETE_TREAT: 'DELETE_TREAT',
  DELETE_TREAT_SUCCESS: 'DELETE_TREAT_SUCCESS',
  DELETE_TREAT_FAILURE: 'DELETE_TREAT_FAILURE',

  REOPEN_TREAT: 'REOPEN_TREAT',
  REOPEN_TREAT_SUCCESS: 'REOPEN_TREAT_SUCCESS',
  REOPEN_TREAT_FAILURE: 'REOPEN_TREAT_FAILURE',

  DUPLICATE_TREAT: 'DUPLICATE_TREAT',
  DUPLICATE_TREAT_SUCCESS: 'DUPLICATE_TREAT_SUCCESS',
  DUPLICATE_TREAT_FAILURE: 'DUPLICATE_TREAT_FAILURE',

  SEND_MESSAGE: 'SEND_MESSAGE',
  SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
  SEND_MESSAGE_FAILURE: 'SEND_MESSAGE_FAILURE',

  NEW_MESSAGE: 'NEW_MESSAGE',

  SEND_REQUEST_TO_OWNER: 'SEND_REQUEST_TO_OWNER',
  SEND_REQUEST_TO_OWNER_SUCCESS: 'SEND_REQUEST_TO_OWNER_SUCCESS',
  SEND_REQUEST_TO_OWNER_FAILURE: 'SEND_REQUEST_TO_OWNER_FAILURE',

  UPLOAD_PET_OWNER_FILES: 'UPLOAD_PET_OWNER_FILES',
  UPLOAD_PET_OWNER_FILES_SUCCESS: 'UPLOAD_PET_OWNER_FILES_SUCCESS',
  UPLOAD_PET_OWNER_FILES_FAILURE: 'UPLOAD_PET_OWNER_FILES_FAILURE',

  UPLOAD_INVOICE: 'UPLOAD_INVOICE',
  UPLOAD_INVOICE_SUCCESS: 'UPLOAD_INVOICE_SUCCESS',
  UPLOAD_INVOICE_FAILURE: 'UPLOAD_INVOICE_FAILURE',

  SET_INVOICE: 'SET_INVOICE',

  DELETE_INVOICE: 'DELETE_INVOICE',
  DELETE_INVOICE_SUCCESS: 'DELETE_INVOICE_SUCCESS',
  DELETE_INVOICE_FAILURE: 'DELETE_INVOICE_FAILURE',

  GET_NOTES: 'GET_NOTES',
  GET_NOTES_SUCCESS: 'GET_NOTES_SUCCESS',
  GET_NOTES_FAILURE: 'GET_NOTES_FAILURE',

  CREATE_NOTE: 'CREATE_NOTE',
  CREATE_NOTE_SUCCESS: 'CREATE_NOTE_SUCCESS',
  CREATE_NOTE_FAILURE: 'CREATE_NOTE_FAILURE',

  DELETE_NOTE: 'DELETE_NOTE',
  DELETE_NOTE_SUCCESS: 'DELETE_NOTE_SUCCESS',
  DELETE_NOTE_FAILURE: 'DELETE_NOTE_FAILURE',

  UPDATE_NOTE: 'UPDATE_NOTE',
  UPDATE_NOTE_SUCCESS: 'UPDATE_NOTE_SUCCESS',
  UPDATE_NOTE_FAILURE: 'UPDATE_NOTE_FAILURE',

  SAVE_DEKNINGSTILSAGN: 'SAVE_DEKNINGSTILSAGN',
  SAVE_DEKNINGSTILSAGN_SUCCESS: 'SAVE_DEKNINGSTILSAGN_SUCCESS',
  SAVE_DEKNINGSTILSAGN_FAILURE: 'SAVE_DEKNINGSTILSAGN_FAILURE',

  INIT_DEKNINGSTILSAGN: 'INIT_DEKNINGSTILSAGN',
};

export default actions;
