const actions = {
  GET_VETS: 'GET_VETS',
  GET_VETS_SUCCESS: 'GET_VETS_SUCCESS',
  GET_VETS_FAILURE: 'GET_VETS_FAILURE',

  GET_VET: 'GET_VET',
  GET_VET_SUCCESS: 'GET_VET_SUCCESS',
  GET_VET_FAILURE: 'GET_VET_FAILURE',

  ADD_VET: 'ADD_VET',
  ADD_VET_SUCCESS: 'ADD_VET_SUCCESS',
  ADD_VET_FAILURE: 'ADD_VET_FAILURE',

  UPDATE_VET: 'UPDATE_VET',
  UPDATE_VET_SUCCESS: 'UPDATE_VET_SUCCESS',
  UPDATE_VET_FAILURE: 'UPDATE_VET_FAILURE',

  GET_INSURANCE_COMPANIES: 'GET_INSURANCE_COMPANIES',
  GET_INSURANCE_COMPANIES_SUCCESS: 'GET_INSURANCE_COMPANIES_SUCCESS',
  GET_INSURANCE_COMPANIES_FAILURE: 'GET_INSURANCE_COMPANIES_FAILURE',

  GET_INSURANCE_COMPANY: 'GET_INSURANCE_COMPANY',
  GET_INSURANCE_COMPANY_SUCCESS: 'GET_INSURANCE_COMPANY_SUCCESS',
  GET_INSURANCE_COMPANY_FAILURE: 'GET_INSURANCE_COMPANY_FAILURE',

  ADD_INSURANCE_COMPANY: 'ADD_INSURANCE_COMPANY',
  ADD_INSURANCE_COMPANY_SUCCESS: 'ADD_INSURANCE_COMPANY_SUCCESS',
  ADD_INSURANCE_COMPANY_FAILURE: 'ADD_INSURANCE_COMPANY_FAILURE',

  UPDATE_INSURANCE_COMPANY: 'UPDATE_INSURANCE_COMPANY',
  UPDATE_INSURANCE_COMPANY_SUCCESS: 'UPDATE_INSURANCE_COMPANY_SUCCESS',
  UPDATE_INSURANCE_COMPANY_FAILURE: 'UPDATE_INSURANCE_COMPANY_FAILURE',

  GET_TREATS: 'GET_TREATS',
  GET_TREATS_SUCCESS: 'GET_TREATS_SUCCESS',
  GET_TREATS_FAILURE: 'GET_TREATS_FAILURE',
};

export default actions;
